### ISSUE TITLE
Torcherino settings not saving?

### ISSUE THREAD

**Issue by NinjaPhenix** [NinjaPhenix/Torcherino#11]
Torcherino 9.0.0
There seems to be a very obscure issue in which value update packet is failing to send or the data is failing to save. Tried testing different Window OS versions, Java versions and recreating modpack with no prevail. Going to leave this open in case anyone can reproduce this issue and able to debug it.

**Comment by NinjaPhenix** [comment]
`[16:56:40.696] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server java.lang.NullPointerException: null at torcherino.network.ValueUpdateMessage.lambda$handle$0(ValueUpdateMessage.java:58) ~[?:9.0.0] {} at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:185) ~[?:?] {} at torcherino.network.ValueUpdateMessage.handle(ValueUpdateMessage.java:50) ~[?:9.0.0] {} at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:114) ~[?:?] {} at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_211] {} at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:114) ~[?:?] {} at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:147) ~[?:?] {} at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:64) ~[?:?] {} at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-0.10.2-service.jar:?] {} at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-0.10.2-service.jar:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.2-service.jar:?] {} at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:82) ~[?:?] {} at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:67) ~[?:?] {} at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_211] {} at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:67) ~[?:?] {} at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1304) ~[?:?] {} at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {pl:runtimedistcleaner:A} at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {pl:runtimedistcleaner:A} at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?] {} at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {} at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) [?:?] {pl:accesstransformer:B} at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {} at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) [?:?] {pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:99) [?:?] {pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:662) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A} at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}`

**Comment by NinjaPhenix** [comment]
Think I've found a fix (released in 9.0.1 and 8.1.4), this will remain open untill original reporter verifies it works for them.

**Comment by NinjaPhenix** [comment]
Confirmed to be working.
